project:
  type: website
  output-dir: docs
  preview: 
    # port: 5556
    # browser: true
    # watch-inputs: true
    navigate: true

website:
  title: "Shingo Nitta"
  # favicon: "{{< fluent animal-turtle-20-regular >}}"
  # site-url: https://shingonitta.com
  # repo-url: https://github.com/ningositta/ningositta.github.io
  navbar:
    left:
      - href: index.qmd
        text: "{{< iconify material-symbols home-outline >}}Home"
      - text: "{{< iconify gg profile >}}Profile"
        file: profile/index.qmd
      - text: "{{< iconify ph book-open-bold >}}Research"
        file: research/index.qmd
      - text: "{{< iconify ph pencil-line >}}Notes"
        file: notes/index.qmd

# {{< iconify material-symbols home-outline >}}

format:
  html:
    theme: 
      light: [simplex, format/custom.scss]
      dark: [darkly, format/custom.scss]
    linkcolor: red
    # - format/custom.scss

# simplex