project:
  type: website
  output-dir: docs
  preview: 
    # port: 5556
    # browser: true
    # watch-inputs: true
    navigate: true

website:
  title: "Shingo Nitta"
  # favicon: "{{< fluent animal-turtle-20-regular >}}"
  # site-url: https://shingonitta.com
  # repo-url: https://github.com/ningositta/ningositta.github.io
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Profile
        file: profile/index.qmd
      - text: Research
        file: research/index.qmd
      - text: Notes
        file: notes/index.qmd

format:
  html:
    theme: [simplex, format/custom.scss]
    linkcolor: red
    # - format/custom.scss

# simplex